default:
  image: node:18-alpine
  tags:
    - docker

cache:
  key: CI_COMMIT_REF_SLUG
  paths:
    - node_modules/
  policy: pull

stages:
  - prepare
  - lint
  - test
  - build

prepare:
  stage: prepare
  cache:
    key: CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
    when: on_success
    policy: pull-push
  script:
    - echo "Installing dependencies..."
    - npm ci

lint:
  stage: lint
  needs: [ prepare ]
  script:
    - echo "Running linting..."
    - npm run lint

unit-test:
  stage: test
  needs: [ prepare ]
  script:
    - echo "Running unit tests..."
    - npm run test:cov

e2e-test:
  stage: test
  needs: [ prepare ]
  script:
    - echo "Running end-to-end tests..."
    - npm run test:e2e

build:
  stage: build
  needs: [ prepare, lint, unit-test, e2e-test ]
  script:
    - echo "Building project..."
    - npm run build
