image: node:18-alpine

.install_dependencies: &install_dependencies
  script:
    - echo "Installing dependencies..."
    - npm ci

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull

stages:
  - lint
  - unit-test
  - e2e-test
  - build

lint:
  stage: lint
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    when: on_success
    policy: pull-push
  <<: *install_dependencies
  script:
    - echo "Running linting..."
    - npm run lint

unit-test:
  stage: unit-test
  <<: *install_dependencies
  script:
    - echo "Running unit tests..."
    - npm run test:cov

e2e-test:
  stage: e2e-test
  <<: *install_dependencies
  script:
    - echo "Running end-to-end tests..."
    - npm run test:e2e

build:
  stage: build
  <<: *install_dependencies
  script:
    - echo "Building project..."
    - npm run build
