stages:
  - lint
  - unit-test
  - e2e-test
  - build

lint:
  stage: lint
  image: node:18-alpine
  tags:
    - docker
  script:
    - echo "Running lint"
    - npm ci
    - npm run lint

unit-test:
  stage: unit-test
  image: node:18-alpine
  tags:
    - docker
  script:
    - echo "Running unit tests"
    - npm ci
    - echo "Running unit tests"
    - npm run test:cov

e2e-test:
  stage: e2e-test
  image: node:18-alpine
  tags:
    - docker
  script:
    - echo "Running e2e tests"
    - npm ci
    - echo "Running e2e tests"
    - npm run test:e2e

build:
  stage: build
  image: node:18-alpine
  tags:
    - docker
  script:
    - echo "Running npm build"
    - npm ci
    - echo "Running npm build"
    - npm run build

