stages:
  - lint
  - unit-test
  - build

lint:
  stage: lint
  image: node:18-alpine
  tags:
    - docker
  script:
    - npm ci
    - npm run lint

unit-test:
  stage: unit-test
  image: node:18-alpine
  tags:
    - docker
  script:
    - npm ci
    - echo "Running unit tests"
    - npm run test:cov

build:
  stage: build
  image: node:18-alpine
  tags:
    - docker
  script:
    - npm ci
    - echo "Running npm build"
    - npm run build


#build:
#  stage: build
#  image: docker:dind
#  tags:
#    - docker
#  script:
#    - echo $CI_REGISTRY
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - docker build -t $CI_REGISTRY/api:latest .
#    - docker push $CI_REGISTRY/api:latest
