version: '3.9'

services:
  mariadb:
    image: mariadb
    hostname: db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: api
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpwd
    restart: always
    ports:
      - "0.0.0.0:3306:3306"
